### ISSUE TITLE
designer: create logo

### ISSUE THREAD

**Issue by MalloZup** [MalloZup/kubeojo#2]
create logo for kubeojo

It should be something with an eye for having control and something that would also give ideas for analyze/forensic  of tests.
It should be also something relaxed and funny, not a big brother eye :rofl:

**Comment by area55git** [comment]
Hi @MalloZup Perfect, I'm going to work on a proposal

**Comment by MalloZup** [comment]
thx @area55git  really cool :cupid:  take your time no pb :1st_place_medal: :sun_with_face: :beach_umbrella: :smile:

**Comment by area55git** [comment]
Hi @MalloZup What do you think of these proposals?

[![LOGO_PROPOSAL_FOR_KUBEOJO.jpg](https://s8.postimg.cc/71fi4ezg5/LOGO_PROPOSAL_FOR_KUBEOJO.jpg)](https://postimg.cc/image/ufnhgchdd/)

**Comment by MalloZup** [comment]
@area55git  nice! :heart_eyes: 

I really like the 2nd one!

Feel free to submit a pr with 2nd on.

You can put the logo in help dir!

awesome :trophy:

**Comment by area55git** [comment]
Perfect, I will prepare the final files.

**Comment by area55git** [comment]
@MalloZup confirm if you like it like that?

[![LOGO_KUBEOJO.jpg](https://s8.postimg.cc/aa2d0pa6t/LOGO_KUBEOJO.jpg)](https://postimg.cc/image/bp3xpfb9t/)

**Comment by MalloZup** [comment]
@area55git wow really nice ! now you make me dubious  i like both of them.. :+1:  i will ping you tomorrow i will show the logo some friends so i can have more opinion on it.
:heart_eyes:

**Comment by area55git** [comment]
The two are the same logo one in vertical version and the other in horizontal version. I'll send you the 2 in PNG, SVG and other formats. The last ones are the icons.

**Comment by MalloZup** [comment]
@area55git  thanks a lot! after some thinking i like  the one in the middle, horizonal version.

Feel free to do a PR i will merge it ! :cupid:

**Comment by area55git** [comment]
### [FILE DOWNLOAD](https://drive.google.com/open?id=1EnH8o4Oz_p86KQbUBJaeSc6SDDKrBpS6)

[![DERECHOS.jpg](https://s33.postimg.cc/okusqx58v/DERECHOS.jpg)](https://postimg.cc/image/4q8r4sq17/)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).
