### ISSUE TITLE
tests the phoenix app

### ISSUE THREAD

**Issue by MalloZup** [MalloZup/kubeojo#8]
Implement tests automated in travis-ci for webapp and databases side.

**Comment by MalloZup** [comment]
The issue is too old. This comment is autogenerated by blacktango

**Comment by MalloZup** [comment]
The issue is too old. This comment is autogenerated by blacktango

**Comment by MalloZup** [comment]
[autogenerated with https://github.com/MalloZup/doghub] issue older then 10days. Please update the issue or close it

**Comment by jamessral** [comment]
I could start adding some tests. It would be a good way for me to dip my toes into Elixir!

**Comment by MalloZup** [comment]
feel free @jamessral

**Comment by MalloZup** [comment]
I think for moment the test are ok
